name: Workflow

on:
  push:
    branches:
      - test_application
  workflow_dispatch:
jobs:
  code-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          python3.9 -m venv env
          source env/bin/activate
          pip install -r requirements.txt
          python app.py
